[package]
name = "corsairust-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hidapi = "2.1.3"
rusb = "0.9.1"
libusb1-sys = "0.6.4"

[features]
vendored = ["libusb1-sys/vendored"]