[package]
name = "corsairust-host"
version = "0.1.0"
edition = "2021"

[lib]
path = "rust/src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.75"
cxx-qt = "0.4.1"
cxx-qt-lib = "0.4.1"

[build-dependencies]
cxx-qt-build = "0.4"